### PR TITLE
bump to 5.13.2

### PR DESCRIPTION
**Pull request by Dominator008**
This includes a fix for a gutter rendering problem.

### CODE REVIEW

**Comment by jamesward** [comment]
Can you also set:

    <version>5.13.2-SNAPSHOT</version>

**Comment by Dominator008** [comment]
@jamesward Done.

**Comment by Dominator008** [comment]
Thanks! Have you released it to Maven yet?

**Comment by jamesward** [comment]
Yeah. It usually takes an hour or so to show up there.

**Comment by Dominator008** [comment]
Cool, thanks!

**Pull request merged**
